//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamMover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lutador
    {
        public int Id { get; set; }
        public Nullable<double> Exp { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Nome { get; set; }
        public string Universo { get; set; }
        public string Autor { get; set; }
        public string Portrait { get; set; }
        public string Stand { get; set; }
    }
}
