//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamMover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int Id { get; set; }
        public Nullable<int> idPerdedor { get; set; }
        public Nullable<int> IdVencedor { get; set; }
        public Nullable<System.DateTime> DataPartida { get; set; }
        public Nullable<int> IdLutadorCasa { get; set; }
        public Nullable<int> IdLutadorVisitante { get; set; }
        public Nullable<int> PontosVencedor { get; set; }
        public Nullable<int> PontosPerdedor { get; set; }
    }
}
